feat: add test CI step

diff --git a/.github/workflows/backend-CI.yml b/.github/workflows/backend-CI.yml
--- a/.github/workflows/backend-CI.yml
+++ b/.github/workflows/backend-CI.yml
@@ -27,7 +27,23 @@ jobs:
           fi
         env:
           GO111MODULE: on
+
       - name: Build
         run: cd tides-server/cmd && go build -v .
         env:
           GO111MODULE: on
+
+  test:
+    name: Test
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: gofmt
+        run: |
+        # output files that doesn't conform to the format specification
+          cd tides-server && ls -p | grep -v vendor | grep -v swagger | grep "/$" | xargs gofmt -l -s
+        # optional: failure to comply with the specification forces the task to fail
+          # exit $(cd tides-server && ls -p | grep -v vendor | grep -v swagger | grep "/$" | xargs gofmt -l -s | wc -l)
+
+      - name: gotest
+        run: cd tides-server && go test ./...
